### ISSUE TITLE
Getting error on running pear dev

### ISSUE THREAD

**Issue by all2pie** [holepunchto/pear-cli#2]
## Reproduction

1. make a new directory
2. run `pear init -y`
3. run `pear dev`

## Issue

Initially I was getting the following error which I resolved by restarting the pear runtime

```
x An error occured
TypeError: ipc.start is not a function
    at run (file:///C:/Users/mhari/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/lib/run.js:58:71)       
    at run (file:///C:/Users/mhari/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/cmd/run.js:58:51)       
    at Object.dev (file:///C:/Users/mhari/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/cmd/index.js:68:36)
    at Cmd.run (file:///C:/Users/mhari/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/cmd/index.js:51:38) 
    at module.exports (file:///C:/Users/mhari/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/cmd/index.js:79:13)
    at cli (file:///C:/Users/mhari/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/cli.js:19:9)
```

Currently the dev tools and the app is launching but it's giving this error

`Cannot read properties of undefined (reading 'get')`

And on the console this error is logged

`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

## Environment
OS: Windows 11
Nodejs: v18.13.0
npm: 8.19.3

**Comment by all2pie** [comment]
I tried with a terminal type project as well by doing 
`pear init -y -t terminal`

Also for that I am getting this error:
`Not Found: "/index.js"`

Seems like pear is not able to detect the current directory or something like that.

I have tried on git bash and cmd.

**Comment by all2pie** [comment]
After restarting my system here are some more logs from the console 

![image](https://github.com/holepunchto/pear-cli/assets/34629684/1768a06a-43c9-42fb-8049-7923002af22f)

Here is the screenshot of the error as well

![image](https://github.com/holepunchto/pear-cli/assets/34629684/b4665bf9-dcf0-49e1-8b76-5db80127bf0d)
